name: 代码质量检查

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置Node.js环境
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 安装依赖
      run: |
        npm install -g htmlhint
        npm install -g stylelint
        npm install -g eslint
        
    - name: 检查HTML代码质量
      run: |
        find . -name "*.html" -not -path "./node_modules/*" -not -path "./.git/*" | xargs htmlhint
        
    - name: 检查CSS代码质量
      run: |
        find . -name "*.css" -not -path "./node_modules/*" -not -path "./.git/*" | xargs stylelint
        
    - name: 检查JavaScript代码质量
      run: |
        find . -name "*.js" -not -path "./node_modules/*" -not -path "./.git/*" | xargs eslint